name: Build Galaxy Watch APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Build Android APK
      working-directory: android
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: galaxy-watch-heartrate-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Create Release APK
      working-directory: android
      run: ./gradlew assembleRelease
      continue-on-error: true
      
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: galaxy-watch-heartrate-release
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 30
      continue-on-error: true